#!/usr/bin/env zsh
# -*- Mode: Shell-script -*-
#
# zshrc --- Z Shell initialisation.
#
# Copyright (c) 2016-2025 Paul Ward <asmodai@gmail.com>
#
# Author:     Paul Ward <asmodai@gmail.com>
# Maintainer: Paul Ward <asmodai@gmail.com>
# Created:    15 Aug 2016 19:03:51
#
# {{{ License:
#
# This program is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY  WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# }}}
# {{{ Commentary:
#
# }}}

# Profile location
export ZSH=${HOME}/.zshrc.d

# Allow scripts to detect this 'library'.
export ZSH_HACKER="true"

# Use case-sensitive completion?
CASE_SENSITIVE="false"

# Use hyphen-insensitive completion?
HYPHEN_INSENSITIVE="true"

# Disable 'ls' colors?
DISABLE_LS_COLORS="false"

# Disable terminal title?
DISABLE_AUTO_TITLE="false"

# Command auto correction?
DISABLE_AUTO_CORRECTION="false"

# Display red dots whilst waiting for completion
COMPLETION_WAITING_DOTS="true"

# Disable mark untracked files as dirty?
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Time stamp output
HIST_STAMPS="yyyy-mm-dd"

# Language setting
export LANG=en_GB.UTF-8

# Unix session defaults.
export EDITOR='vim'
export PAGER='less'

# Now that we have the defaults, let's see if there's a user config to load
if [ -f "${HOME}/.zshrc.conf" ]
then
    source ${HOME}/.zshrc.conf
fi

# Obtain projects directory on this host.
PROJECTS_DIRECTORY="${HOME}/projects"
if [[ -d "${HOME}/Projects" ]]
then
    PROJECTS_DIRECTORY="${HOME}/Projects"
fi
export PROJECTS_DIRECTORY

# Load in utils.
source ${ZSH}/lib/utils.zsh

# Ensure we're in ZSH!
function zshOrDie () {
    if [[ -z "${ZSH_VERSION}" ]];
    then
        printf "This requires ZSH in order to run. You used: %s\n" $SHELL
        exit 1
    fi
}

# Get various paths.
function getPaths() {
    typeset -a paths
    local index=0

    # Set up for Go.
    local godir=""
    test -d "${HOME}/${PROJECTS_DIRECTORY}/Go" && godir="Go"
    test -d "${HOME}/${PROJECTS_DIRECTORY}/go" && godir="go"
    if [[ ! "${godir}" = "" ]]
    then
        export GOPATH="${HOME}/${PROJECTS_DIRECTORY}/${godir}"
        export GOHOME="${GOPATH}"
    fi

    # Set up for Lisp.
    local lispdir=""
    test -d "${HOME}/${PROJECTS_DIRECTORY}/Lisp" && lispdir="Lisp"
    test -d "${HOME}/${PROJECTS_DIRECTORY}/lisp" && lispdir="lisp"
    if [[ ! "${LISPDIR}" = "" ]]
    then
        export LISPPATH="${HOME}/${PROJECTS_DIRECTORY}/${lispdir}"
    fi

    # Keep X11 paths out of this.  If one requires X, then write a plugin
    # that will set up paths if the required X vendor path(s) are available.

    # Set up everything else.
    test -d /bin                   && paths+='/bin'
    test -d /sbin                  && paths+='/sbin'
    test -d /usr/bin               && paths+='/usr/bin'
    test -d /opt/homebrew/bin      && paths+='/opt/homebrew/bin'
    test -d /usr/local/bin         && paths+='/usr/local/bin'
    test -d /usr/sbin              && paths+='/usr/sbin'
    test -d /usr/local/sbin        && paths+='/usr/local/sbin'
    test -d /opt/bin               && paths+='/opt/bin'
    test -d /opt/local/bin         && paths+='/opt/local/bin'
    test -d "${GOPATH}"            && paths+="${GOPATH}/bin"
    test -d "${HOME}/bin"          && paths+="${HOME}/bin"
    test -d "${HOME}/.local/bin"   && paths+="${HOME}/.local/bin"
    test -d "${HOME}/.zshrc.d/bin" && paths+="${HOME}/.zshrc.d/bin"

    # This is a thing on Garuda (maybe Arch too?)
    test -d /usr/bin/vendor_perl   && paths+="/usr/bin/vendor_perl"

    export PATH=${(j;:;)paths}
}

# Boot shell config/
function boot() {
    getPaths
}

zshOrDie
boot

unset boot
unset getPaths
unset zshOrDie

export PATH

source ${ZSH}/boot.zsh

# zshrc ends here.
