#!/usr/bin/env bash

RESET="[0m"
NORM="[0;37m"
BOLD="[1;37m"
DIM="[2;35m"
ITAL="[3;37m"
NPUR="[0;35m"
BPUR="[1;35m"

host=${1:-$(hostname | cut -d. -f1)}
system=$(uname -s)
release=$(uname -r)
machine=$(uname -m)
version=$(uname -v)
domain="retro.lisphacker.home"
other=""

# Fix up system information.
case "${system}:${version}:${release}" in
    Darwin:*:*)
        release=$(/usr/bin/sw_vers -productVersion)
        system="macOS"
        ;;
esac

# Fix up machine type.
case "${machine}" in
    aarch64)
        machine="ARM64"
        ;;

    i86pc|i?86|x86)
        machine="x86"
        ;;

    amd64|x86_64)
        machine="AMD64"
        ;;
esac

# Fix up system type.
case "${system}" in
    Linux) system="GNU/Linux" ;;
esac

# Initial `pretty' string.
pretty="${system} ${release}"

# Do we have a machine type?
if [ "${machine}" != "" ]
then
    pretty="${pretty} - ${machine}"
fi

# Default description.
desc="Yet another Unix host."

# Determine the description.
case "$host" in
    farragut)
        desc="Main GNU/Linux workstation.."
        domain="lisphacker.home"
        ;;

    equinox)
        desc="GNU/Linux workstation."
        domain="lisphacker.home"
        ;;

    sovereign)
        desc="Home automation controller."
        domain="lisphacker.home"
        ;;

    voyager)
        desc="Laptop."
        domain="lisphacker.home"
        ;;

    # VM on voyager.
    daedalus)
        desc="X Window System terminal."
        domain="lisphacker.home"
        ;;

    hubble)
        desc="Ansible and monitoring server."
        domain="lisphacker.home"
        ;;

    epsilon)
        desc="Web server."
        domain="lisphacker.home"
        ;;

    lovell)
        desc="GitLab server."
        domain="lisphacker.home"
        ;;

    enterprise)
        desc="Media server."
        domain="lisphacker.home"
        ;;

    jupiter)
        desc="Security server."
        domain="lisphacker.home"
        ;;

    memory-alpha)
        desc="NAS server."
        domain="lisphacker.home"
        ;;

    scryer)
        desc="Home automation server."
        domain="lisphacker.home"
        ;;

    eclipse)
        desc="Metrics server."
        domain="lisphacker.home"
        ;;

    daystrom)
        desc="Minecraft resource server."
        domain="lisphacker.home"
        ;;

    atlas)
        desc="Minecraft server"
        domain="lisphacker.home"
        ;;

    wormhole)
        desc="PiHole server."
        domain="lisphacker.home"
        ;;

    neutralzone)
        desc="Internet gateway."
        domain="lisphacker.home"
        ;;

    ## To be removed.
    armstrong)
        desc="Retro hardware simulator."
        domain="lisphacker.home"
        ;;

    ## To be removed.
    challenger)
        desc="Dev virtual workstation."
        domain="lisphacker.home"
        ;;

    #
    # Remote systems.
    darkstar)
        desc="DigitalOcean Droplet."
        domain="lisphacker.uk"
        ;;
esac

cat motd.ans
cat <<EOF

  ${DIM}::${NORM} ${BOLD}${host}.${domain}${RESET}
  ${DIM}::${NORM} ${BPUR}${desc}${RESET}
  ${DIM}::${NORM} ${NPUR}${pretty}${RESET}

EOF

# motd ends here.
