#!/usr/bin/env bash

RESET="[0m"
NORM="[0;37m"
BOLD="[1;37m"
DIM="[2;35m"
ITAL="[3;37m"
NPUR="[0;35m"
BPUR="[1;35m"

host=${1:-$(hostname | cut -d. -f1)}
system=$(uname -s)
release=$(uname -r)
machine=$(uname -m)
version=$(uname -v)
domain="retro.lisphacker.home"
other=""

# Allow some things to be set via CLI arg.
case "$1" in
    # Special case for Multics.
    multics|stargazer)
        host="stargazer"
        system="Multics"
        release="12.8"
        machine="DPS-8/M"
        version=""
        ;;

    # Special case for VMS/VAX 7.3.
    wilson|wakata|sharma|chawla|deng)
        host="$1"
        system="OpenVMS/VAX"
        release="7.3"
        machine="VAX"
        version=""
        other="VMS cluster node"
        ;;

    # Special case for VMS/VAX 3.5.
    conrad)
        host="$1"
        system="VAX/VMS"
        release="3.5"
        machine="VAX"
        version=""
        ;;

    # Special case for RSX-11M.
    white)
        host="$1"
        system="RSX-11M-Plus"
        release="v4.6"
        version=""
        machine="PDP-11/70"
        ;;

    # Special case for TOPS-20.
    fei)
        host="$1"
        system="TOPS-20"
        release="v4.1"
        version=""
        machine="PDP-10"
        ;;

    # Special case for 2.11 BSD.
    titov)
        host="$1"
        system="BSD"
        release="2.11"
        machine="PDP-11"
        version=""
        ;;

    # Special case for ULTRIX32.
    volkov)
        host="$1"
        system="ULTRIX32"
        release="2.5"
        machine="VAX-11/780"
        version=""
        ;;

    # Special case for AT&T SVR3.
    borman)
        host="$1"
        system="borman"
        release="3.2.3"
        machine="WE32200"
        version="3"
        ;;

    # Everything else.
    *)
        host="${1-$host}"
        ;;
esac

# Fix up system information.
case "${system}:${version}:${release}" in
    AIX:*:*)
        release="${release}.${version}"
        ;;

    HP-UX:*:*)
        release=$(echo "$release" | cut -d. -f2-)
        ;;

    OSF1:*:*)
        system="OSF/1"
        ;;

    UnixWare:*:*)
        release="$version"
        ;;

    SCO_SV:*:*)
        system="SCO Unix"
        [ -f /etc/scologin ] && {
            system="SCO OpenServer"
            release="${version}"
        }
        ;;

    $host:3:*)
        system="AT&T System V"
        ;;

    machten*:*:*)
        machten=$(/sbin/version)
        system=$(echo "${machten}" | cut -d\  -f1)
        release=$(echo "${machten}" | cut -d\  -f2-)
        ;;

    SunOS:*:5.*)
        system="Solaris";
        release=$(echo ${release} | cut -d. -f2-)
        ;;

    # This might be bogus.  It needs testing on more versions of Mac OS X.
    # I highly doubt this will work on macOS 11 or above, so this is limited
    # to Darwin 5.x.
    Darwin:*:5.*)
        second=$(echo ${release} | cut -d. -f2)
        third=$(echo ${release} | cut -d. -f3)
        system="Mac OS X"
        release=$(echo "10.$((second-1)).$third")
        ;;
esac

# Fix up machine type.
case "${machine}" in
    9000/*)
        machine="PA-RISC"
        ;;

    IBM,*)
        machine="POWER"
        ;;

    aarch64)
        machine="ARM64"
        ;;

    alpha|axp)
        machine="Alpha"
        ;;

    i86pc|i?86|x86)
        machine="x86"
        ;;

    # Might be worth splitting this out so that we can capture the actual
    # vendor -- e.g. NeXT, Sun, etc.
    680?0|next68k|m68k|sun2|sun3)
        machine="68000"
        ;;

    # Maybe one day I'll get an AViiON.
    88???|m88k)
        machine="88000"
        ;;

    amd64|x86_64)
        machine="AMD64"
        ;;

    sun4m)
        machine="MicroSPARC"
        ;;

    sun4u)
        machine="UltraSPARC"
        ;;

    sparc)
        machine="SPARC"
        ;;

    powerpc|Power*Mac*|ppc)
        machine="PowerPC"
        ;;
esac

# Fix up system type.
case "${system}" in
    Linux) system="GNU/Linux" ;;
esac

# Initial `pretty' string.
pretty="${system} ${release}"

# Do we have a machine type?
if [ "${machine}" != "" ]
then
    pretty="${pretty} - ${machine}"
fi

# Other information?
if [ "${other}" != "" ]
then
    pretty="${pretty} - ${other}"
fi

# Default description.
desc="Yet another Unix host."

# Determine the description.
case "$host" in
    farragut)
        desc="Main rig."
        domain="lisphacker.home"
        ;;

    equinox)
        desc="Rig."
        domain="lisphacker.home"
        ;;

    sovereign)
        desc="Home automation controller."
        domain="lisphacker.home"
        ;;

    voyager)
        desc="Laptop."
        domain="lisphacker.home"
        ;;

    daedalus)
        desc="X Window System terminal."
        domain="lisphacker.home"
        ;;

    hubble)
        desc="Ansible and monitoring server."
        domain="lisphacker.home"
        ;;

    epsilon)
        desc="Web server."
        domain="lisphacker.home"
        ;;

    lovell)
        desc="GitLab server."
        domain="lisphacker.home"
        ;;

    enterprise)
        desc="Media server."
        domain="lisphacker.home"
        ;;

    jupiter)
        desc="Security server."
        domain="lisphacker.home"
        ;;

    memory-alpha)
        desc="NAS server."
        domain="lisphacker.home"
        ;;

    scryer)
        desc="Home automation server."
        domain="lisphacker.home"
        ;;

    eclipse)
        desc="Metrics server."
        domain="lisphacker.home"
        ;;

    daystrom)
        desc="Minecraft resource server."
        domain="lisphacker.home"
        ;;

    atlas)
        desc="Minecraft server"
        domain="lisphacker.home"
        ;;

    wormhole)
        desc="PiHole server."
        domain="lisphacker.home"
        ;;

    neutralzone)
        desc="Internet gateway."
        domain="lisphacker.home"
        ;;

    ## To be removed.
    armstrong)
        desc="Retro hardware simulator."
        domain="lisphacker.home"
        ;;

    ## To be removed.
    challenger)
        desc="Dev virtual workstation."
        domain="lisphacker.home"
        ;;

    #
    # Remote systems.
    darkstar)
        desc="DigitalOcean Droplet."
        domain="lisphacker.uk"
        ;;

    #
    # Retro Unix systems.
    borman)       desc="Simulated AT&T 3B2/700 workstation."         ;;
    chawla)       desc="Simulated DEC MicroVAX 3900 server."         ;;
    chen)         desc="UNUSED"                                      ;;
    conrad)       desc="Simulated DEC VAX-11/780 server."            ;;
    deng)         desc="Simulated DEC MicroVAX 3900 server."         ;;
    duke)         desc="Apple PowerBook G4 Aluminium laptop."        ;;
    fisher)       desc="Simulated Intel x86 server."                 ;;
    gagarin)      desc="Fujitsu-Siemens Scenic AB"                   ;;
    garreau)      desc="Apple Quadra 750 workstation."               ;;
    hadfield)     desc="HP 712/60 workstation."                      ;;
    henize)       desc="Apple PowerBook G3 laptop."                  ;;
    kelvin)       desc="Simulated DEC MicroVAX 3100 M96 server."     ;;
    komarov)      desc="IBM RS/6000 Model 44p-170 server."           ;;
    korolev)      desc="Simulated DEC Alpha EV4 server."             ;;
    leonov)       desc="Simulated Intel x86 server."                 ;;
    mukai)        desc="IBM PS/2 Model 80 workstation."              ;;
    polyakov)     desc="DEC Personal Workstation 500au."             ;;
    resnik)       desc="Simulated DEC MicroVAX 3900 server."         ;;
    ride)         desc="DECpc 486-33 PC."                            ;;
    seddon)       desc="Apple PowerBook G4 Titanium laptop."         ;;
    sharma)       desc="Simulated DEC MicroVAX 3900 server."         ;;
    shepard)      desc="Simulated Intel x86 server."                 ;;
    tereshkova)   desc="UNUSED"                                      ;;
    titov)        desc="Simulated DEC PDP-11/93 server."             ;;
    volkov)       desc="Simulated DEC VAX-11/780 server."            ;;
    wakata)       desc="Simulated DEC MicroVAX 3900 server."         ;;
    walker)       desc="Simulated Intel x86 server."                 ;;
    wang)         desc="UNUSED"                                      ;;
    white)        desc="Simulated DEC PDP-11/70 server."             ;;
    whitsun)      desc="Simulated DEC MicroVAX 3900 server."         ;;
    wilson)       desc="Simulated DEC MicroVAX 3900 server."         ;;
    yamato)       desc="Simulated DEC MicroVAX 3900 server."         ;;
    yang)         desc="HP 715/50 workstation."                      ;;
    zhang)        desc="UNUSED"                                      ;;

    #
    # Non-Unix retro systems.
    axiom)        desc="Symbolics virtual Lisp machine."             ;;
    fei)          desc="Simulated DEC PDP-10 server."                ;;
    kranz)        desc="Hercules System 370 mainframe."              ;;
    stargazer)    desc="Simulated Honeywell DPS-8/M mainframe."      ;;

    #
    # Physical retro machines.
    glenn)        desc="Development retro LAN gateway."              ;;
    #glenn)        desc="Honeywell DPS-8/M simulator server."         ;;
    grissom)      desc="SIMH TCP/IP node simulation server."         ;;
    mcdivitt)     desc="SIMH DECnet node simulation server."         ;;
    popovich)     desc="Herules IBM System 370 simulator server."    ;;
    sagan)        desc="Retro LAN gateway."                          ;;

    #
    # Simulated NeXT machines.
    bobko)        desc="Simulated Intel workstation."                ;;
    brand)        desc="Simulated NeXTstation workstation."          ;;
    crippen)      desc="Simulated NeXTcomputer workstation."         ;;
    engle)        desc="Simulated NeXTcomputer workstation."         ;;
    fabian)       desc="Simulated Intel workstation."                ;;
    gibson)       desc="Simulated Intel workstation."                ;;
    hauck)        desc="Simulated NeXTdimension workstation."        ;;
    hawley)       desc="Simulated NeXTstation workstation."          ;;
    lousma)       desc="Simulated NeXTcube workstation."             ;;
    lucid)        desc="Simulated Intel workstation."                ;;
    mattingly)    desc="Simulated Intel workstation."                ;;
    nagel)        desc="Simulated NeXTdimension workstation."        ;;
    shaw)         desc="Sun workstation probably."                   ;;
    truly)        desc="HP 712 possibly."                            ;;
    young)        desc="Simulated NeXTcomputer workstation."         ;;
esac

cat motd.ans
cat <<EOF

  ${DIM}::${NORM} ${BOLD}${host}.${domain}${RESET}
  ${DIM}::${NORM} ${BPUR}${desc}${RESET}
  ${DIM}::${NORM} ${NPUR}${pretty}${RESET}

EOF

# motd ends here.
